name: Compile LaTeX Presentation
on: [ workflow_dispatch ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=out main.tex
        working-directory: presentation

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: main-document
          path: presentation/out/main.pdf
